import type { WeaponCategory, AmmoType, Tier } from "@/config/game";

export type Weapon = {
  id: number;
  name: string;
  nameJa: string;
  slug: string;
  category: WeaponCategory;
  ammoType: AmmoType;
  damage: number;
  headshot: number;
  fireRate: number;
  dps: number;
  magazine: number;
  tier: Tier;
  description: string;
};

export const weapons: Weapon[] = [
  {
    id: 1,
    name: "R-301",
    nameJa: "R-301 カービン",
    slug: "r-301",
    category: "アサルトライフル",
    ammoType: "ライト",
    damage: 14,
    headshot: 25,
    fireRate: 810,
    dps: 189,
    magazine: 18,
    tier: "S",
    description: "安定性と汎用性に優れたアサルトライフル。リコイルが素直で初心者にもおすすめ。中距離で特に強力。",
  },
  {
    id: 2,
    name: "Flatline",
    nameJa: "フラットライン",
    slug: "flatline",
    category: "アサルトライフル",
    ammoType: "ヘビー",
    damage: 18,
    headshot: 32,
    fireRate: 600,
    dps: 180,
    magazine: 20,
    tier: "A",
    description: "高ダメージのヘビーアサルトライフル。リコイルは独特だが、マスターすれば近〜中距離で非常に強力。",
  },
  {
    id: 3,
    name: "R-99",
    nameJa: "R-99",
    slug: "r-99",
    category: "サブマシンガン",
    ammoType: "ライト",
    damage: 11,
    headshot: 17,
    fireRate: 1080,
    dps: 198,
    magazine: 20,
    tier: "A",
    description: "超高速連射SMG。近距離での瞬間火力はトップクラス。弾持ちが悪いのでリロード管理が重要。",
  },
  {
    id: 4,
    name: "Wingman",
    nameJa: "ウィングマン",
    slug: "wingman",
    category: "ピストル",
    ammoType: "スナイパー",
    damage: 45,
    headshot: 97,
    fireRate: 156,
    dps: 117,
    magazine: 6,
    tier: "S",
    description: "高威力リボルバー。ヘッドショットダメージが非常に高い。エイム力がそのまま火力に直結する上級者向け武器。",
  },
  {
    id: 5,
    name: "Peacekeeper",
    nameJa: "ピースキーパー",
    slug: "peacekeeper",
    category: "ショットガン",
    ammoType: "ショットガン",
    damage: 99,
    headshot: 143,
    fireRate: 58,
    dps: 96,
    magazine: 5,
    tier: "A",
    description: "レバーアクション式ショットガン。チョークで絞ると中距離でもダメージが通る。タイミングが重要な武器。",
  },
  {
    id: 6,
    name: "Volt",
    nameJa: "ボルト",
    slug: "volt",
    category: "サブマシンガン",
    ammoType: "エネルギー",
    damage: 15,
    headshot: 23,
    fireRate: 783,
    dps: 195,
    magazine: 19,
    tier: "A",
    description: "エネルギーSMG。反動が少なく当てやすい。近〜中距離のバランスが良い万能武器。",
  },
  {
    id: 7,
    name: "Mastiff",
    nameJa: "マスティフ",
    slug: "mastiff",
    category: "ショットガン",
    ammoType: "ショットガン",
    damage: 88,
    headshot: 128,
    fireRate: 66,
    dps: 96,
    magazine: 6,
    tier: "B",
    description: "セミオートショットガン。横に広がる散弾パターンが特徴。ADSすると散弾が絞られる。",
  },
  {
    id: 8,
    name: "Longbow",
    nameJa: "ロングボウ",
    slug: "longbow",
    category: "マークスマンライフル",
    ammoType: "スナイパー",
    damage: 55,
    headshot: 110,
    fireRate: 78,
    dps: 72,
    magazine: 6,
    tier: "B",
    description: "セミオートのマークスマンライフル。中〜遠距離でのポーク（削り）に最適。スナイパースコープ装着可能。",
  },
  {
    id: 9,
    name: "Devotion",
    nameJa: "ディヴォーション",
    slug: "devotion",
    category: "ライトマシンガン",
    ammoType: "エネルギー",
    damage: 16,
    headshot: 24,
    fireRate: 900,
    dps: 240,
    magazine: 36,
    tier: "B",
    description: "スピンアップ式LMG。最大回転数に達するとDPSはゲーム最高クラス。ターボチャージャーで即座に最大火力。",
  },
  {
    id: 10,
    name: "Sentinel",
    nameJa: "センチネル",
    slug: "sentinel",
    category: "スナイパーライフル",
    ammoType: "スナイパー",
    damage: 70,
    headshot: 140,
    fireRate: 31,
    dps: 36,
    magazine: 4,
    tier: "C",
    description: "ボルトアクション式スナイパーライフル。シールドセルでチャージするとシールドへの追加ダメージ。",
  },
  {
    id: 11,
    name: "Prowler",
    nameJa: "プラウラー",
    slug: "prowler",
    category: "サブマシンガン",
    ammoType: "ヘビー",
    damage: 15,
    headshot: 23,
    fireRate: 800,
    dps: 200,
    magazine: 20,
    tier: "B",
    description: "5点バースト式SMG。バースト射撃の全弾命中時の瞬間火力は非常に高い。",
  },
  {
    id: 12,
    name: "Havoc",
    nameJa: "ハボック",
    slug: "havoc",
    category: "アサルトライフル",
    ammoType: "エネルギー",
    damage: 18,
    headshot: 32,
    fireRate: 672,
    dps: 201,
    magazine: 24,
    tier: "B",
    description: "チャージ式エネルギーAR。撃ち始めにスピンアップがあるが、ターボチャージャーで解消可能。高DPS。",
  },
];
