/**
 * LINE Rich Menu configuration and registration for Litwill Garden.
 *
 * Defines the 5-area rich menu linking users to key sections of the site
 * and external channels.
 *
 * @module line-marketing/rich-menu
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** A single tap-area inside a LINE rich menu. */
export type RichMenuArea = {
  bounds: { x: number; y: number; width: number; height: number };
  action: {
    type: "uri" | "postback";
    uri?: string;
    label: string;
    data?: string;
  };
};

/** Payload sent to the LINE API to create a rich menu. */
export type RichMenuPayload = {
  size: { width: number; height: number };
  selected: boolean;
  name: string;
  chatBarText: string;
  areas: RichMenuArea[];
};

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/**
 * Rich menu item definitions.
 *
 * Each item maps a label (displayed text) to the destination URL.
 */
export const RICH_MENU_CONFIG = {
  items: [
    { label: "攻略記事", url: "https://litwill-garden.com/guides" },
    { label: "無料ガイド", url: "https://litwill-garden.com/guides/beginner" },
    { label: "有料コンテンツ", url: "https://note.com/litwill_garden" },
    { label: "YouTube", url: "https://www.youtube.com/@litwill-garden" },
    { label: "チーム情報", url: "https://litwill-garden.com/team" },
  ],
} as const;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Builds the LINE rich menu creation API payload.
 *
 * The menu is laid out as a 2500 x 1686 image with a top row of 3 items
 * and a bottom row of 2 items.
 *
 * @returns A `RichMenuPayload` ready to be sent to the LINE API.
 */
export function createRichMenuPayload(): RichMenuPayload {
  const width = 2500;
  const height = 1686;
  const topRowHeight = Math.floor(height / 2); // 843
  const bottomRowHeight = height - topRowHeight; // 843
  const topItemWidth = Math.floor(width / 3); // 833
  const bottomItemWidth = Math.floor(width / 2); // 1250

  const items = RICH_MENU_CONFIG.items;

  const areas: RichMenuArea[] = [
    // Top row – 3 items
    {
      bounds: { x: 0, y: 0, width: topItemWidth, height: topRowHeight },
      action: { type: "uri", uri: items[0].url, label: items[0].label },
    },
    {
      bounds: { x: topItemWidth, y: 0, width: topItemWidth, height: topRowHeight },
      action: { type: "uri", uri: items[1].url, label: items[1].label },
    },
    {
      bounds: {
        x: topItemWidth * 2,
        y: 0,
        width: width - topItemWidth * 2,
        height: topRowHeight,
      },
      action: { type: "uri", uri: items[2].url, label: items[2].label },
    },
    // Bottom row – 2 items
    {
      bounds: { x: 0, y: topRowHeight, width: bottomItemWidth, height: bottomRowHeight },
      action: { type: "uri", uri: items[3].url, label: items[3].label },
    },
    {
      bounds: {
        x: bottomItemWidth,
        y: topRowHeight,
        width: width - bottomItemWidth,
        height: bottomRowHeight,
      },
      action: { type: "uri", uri: items[4].url, label: items[4].label },
    },
  ];

  return {
    size: { width, height },
    selected: true,
    name: "Litwill Garden メインメニュー",
    chatBarText: "メニューを開く",
    areas,
  };
}

/**
 * Registers the rich menu with the LINE API and returns the created rich menu ID.
 *
 * Calls `POST https://api.line.me/v2/bot/richmenu` with the payload
 * generated by {@link createRichMenuPayload}.
 *
 * @returns The `richMenuId` string assigned by LINE.
 * @throws If the LINE API request fails.
 */
export async function registerRichMenu(): Promise<string> {
  const token = process.env.LINE_CHANNEL_ACCESS_TOKEN ?? "";
  const payload = createRichMenuPayload();

  const res = await fetch("https://api.line.me/v2/bot/richmenu", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify(payload),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Failed to register rich menu: ${res.status} ${text}`);
  }

  const data = (await res.json()) as { richMenuId: string };
  return data.richMenuId;
}
